# Generated by Django 6.1 on 2026-08-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_shopprofile_wholesaler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_code', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('gst', models.FloatField()),
                ('supplier', models.CharField(max_length=40)),
                ('batch_number', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('minimum_stock_level', models.IntegerField()),
                ('wholesaler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='invoices.wholesalerprofile')),
            ],
        ),
    ]
