# Generated by Django 6.1 on 2026-08-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stockforwholesaler',
        ),
    ]
