# Generated by Django 6.1 on 2026-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_stock_stockforwholesaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockforwholesaler',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='purchase_invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='warehouse',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
