# Generated by Django 6.1 on 2026-08-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_stockforwholesaler_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockforwholesaler',
            old_name='mrp',
            new_name='mrp_per_unit',
        ),
        migrations.RenameField(
            model_name='stockforwholesaler',
            old_name='unit',
            new_name='units_per_box',
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='purchase_price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='selling_price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockforwholesaler',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
