# Generated by Django 6.1 on 2026-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_rename_mrp_stockforwholesaler_mrp_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockforwholesaler',
            name='batch_number',
            field=models.CharField(),
        ),
    ]
