# Generated by Django 6.1 on 2026-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_stockforwholesaler_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockforwholesaler',
            name='batch_number',
            field=models.CharField(max_length=40),
        ),
    ]
