# Generated by Django 6.1 on 2026-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_stockforwholesaler_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockforwholesaler',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
